import { BaseRemoteControlAction } from '@/types';
import {
  PoweroffOutlined,
  WarningOutlined,
  MinusOutlined,
  PlusOutlined,
  UpOutlined,
  DownOutlined,
  BackwardOutlined,
  ForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  PauseOutlined,
  BorderOutlined,
  HomeOutlined,
  PlayCircleOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  BarcodeOutlined,
  QuestionOutlined,
} from '@ant-design/icons';

export const BRAVIA_ACTIONS: Record<string, BaseRemoteControlAction> = {
  Num1: {
    label: 'Num1',
    value: 'AAAAAQAAAAEAAAAAAw==',
    x: 11,
    y: 0,
    icon: <>1</>,
  },
  Num2: {
    label: 'Num2',
    value: 'AAAAAQAAAAEAAAABAw==',
    x: 11,
    y: 2,
    icon: <>2</>,
  },
  Num3: {
    label: 'Num3',
    value: 'AAAAAQAAAAEAAAACAw==',
    x: 11,
    y: 4,
    icon: <>3</>,
  },
  Num4: {
    label: 'Num4',
    value: 'AAAAAQAAAAEAAAADAw==',
    x: 12,
    y: 0,
    icon: <>4</>,
  },
  Num5: {
    label: 'Num5',
    value: 'AAAAAQAAAAEAAAAEAw==',
    x: 12,
    y: 2,
    icon: <>5</>,
  },
  Num6: {
    label: 'Num6',
    value: 'AAAAAQAAAAEAAAAFAw==',
    x: 12,
    y: 4,
    icon: <>6</>,
  },
  Num7: {
    label: 'Num7',
    value: 'AAAAAQAAAAEAAAAGAw==',
    x: 13,
    y: 0,
    icon: <>7</>,
  },
  Num8: {
    label: 'Num8',
    value: 'AAAAAQAAAAEAAAAHAw==',
    x: 13,
    y: 2,
    icon: <>8</>,
  },
  Num9: {
    label: 'Num9',
    value: 'AAAAAQAAAAEAAAAIAw==',
    x: 13,
    y: 4,
    icon: <>9</>,
  },
  Num11: {
    label: 'Num11',
    value: 'AAAAAQAAAAEAAAAKAw==',
    x: 14,
    y: 0,
    icon: <>11</>,
  },
  Num12: {
    label: 'Num12',
    value: 'AAAAAQAAAAEAAAALAw==',
    x: 14,
    y: 2,
    icon: <>12</>,
  },
  Num0: {
    label: 'Num0',
    value: 'AAAAAQAAAAEAAAAJAw==',
    x: 14,
    y: 4,
    icon: <>0</>,
  },

  Enter: {
    label: 'Enter',
    value: 'AAAAAQAAAAEAAAALAw==',
    x: 7,
    y: 2,
    icon: <>OK</>,
  },

  Netflix: {
    label: 'Netflix',
    value: 'AAAAAgAAABoAAAB8Aw==',
    x: 6,
    y: 4,
    icon: <>NETFLIX</>,
  },
  ChannelUp: {
    label: 'ChannelUp',
    value: 'AAAAAQAAAAEAAAAQAw==',
    x: 15,
    y: 3,
    icon: <UpOutlined />,
  },
  ChannelDown: {
    label: 'ChannelDown',
    value: 'AAAAAQAAAAEAAAARAw==',
    x: 16,
    y: 3,
    icon: <DownOutlined />,
  },
  VolumeUp: {
    label: 'VolumeUp',
    value: 'AAAAAQAAAAEAAAASAw==',
    x: 15,
    y: 1,
    icon: <PlusOutlined />,
  },
  VolumeDown: {
    label: 'VolumeDown',
    value: 'AAAAAQAAAAEAAAATAw==',
    x: 16,
    y: 1,
    icon: <MinusOutlined />,
  },
  Mute: {
    label: 'Mute',
    value: 'AAAAAQAAAAEAAAAUAw==',
    x: 15,
    y: 0,
    icon: <>MUTE</>,
  },
  Audio: {
    label: 'Audio',
    value: 'AAAAAQAAAAEAAAAXAw==',
    x: 15,
    y: 4,
    icon: <>AUDIO</>,
  },
  Input: {
    label: 'Input',
    value: 'AAAAAQAAAAEAAAAlAw==',
    x: 0,
    y: 0,
    icon: <>INPUT</>,
  },

  PowerOff: {
    label: 'PowerOff',
    value: 'AAAAAQAAAAEAAAAvAw==',
    x: 0,
    y: 4,
    icon: <PoweroffOutlined />,
  },

  Right: {
    label: 'Right',
    value: 'AAAAAQAAAAEAAAAzAw==',
    x: 7,
    y: 4,
    icon: <CaretRightOutlined />,
  },
  Left: {
    label: 'Left',
    value: 'AAAAAQAAAAEAAAA0Aw==',
    x: 7,
    y: 0,
    icon: <CaretLeftOutlined />,
  },

  Home: {
    label: 'Home',
    value: 'AAAAAQAAAAEAAABgAw==',
    x: 9,
    y: 2,
    icon: <HomeOutlined />,
  },

  Up: {
    label: 'Up',
    value: 'AAAAAQAAAAEAAAB0Aw==',
    x: 6,
    y: 2,
    icon: <CaretUpOutlined />,
  },
  Down: {
    label: 'Down',
    value: 'AAAAAQAAAAEAAAB1Aw==',
    x: 8,
    y: 2,
    icon: <CaretDownOutlined />,
  },

  Stop: {
    label: 'Stop',
    value: 'AAAAAgAAAJcAAAAYAw==',
    x: 2,
    y: 3,
    icon: <BorderOutlined />,
  },
  Pause: {
    label: 'Pause',
    value: 'AAAAAgAAAJcAAAAZAw==',
    x: 2,
    y: 1,
    icon: <PauseOutlined />,
  },
  Play: {
    label: 'Play',
    value: 'AAAAAgAAAJcAAAAaAw==',
    x: 3,
    y: 2,
    icon: <PlayCircleOutlined />,
  },
  Rewind: {
    label: 'Rewind',
    value: 'AAAAAgAAAJcAAAAbAw==',
    x: 2,
    y: 0,
    icon: <FastBackwardOutlined />,
  },
  Forward: {
    label: 'Forward',
    value: 'AAAAAgAAAJcAAAAcAw==',
    x: 2,
    y: 4,
    icon: <FastForwardOutlined />,
  },

  Return: {
    label: 'Return',
    value: 'AAAAAgAAAJcAAAAjAw==',
    x: 8,
    y: 0,
    icon: <>RETURN</>,
  },
  Blue: {
    label: 'Blue',
    value: 'AAAAAgAAAJcAAAAkAw==',
    x: 5,
    y: 4,
    icon: <div style={{ background: 'blue' }}>&nbsp;</div>,
  },
  Red: {
    label: 'Red',
    value: 'AAAAAgAAAJcAAAAlAw==',
    x: 5,
    y: 0,
    icon: <div style={{ background: 'red' }}>&nbsp;</div>,
  },
  Green: {
    label: 'Green',
    value: 'AAAAAgAAAJcAAAAmAw==',
    x: 5,
    y: 1,
    icon: <div style={{ background: 'green' }}>&nbsp;</div>,
  },
  Yellow: {
    label: 'Yellow',
    value: 'AAAAAgAAAJcAAAAnAw==',
    x: 5,
    y: 3,
    icon: <div style={{ background: 'yellow' }}>&nbsp;</div>,
  },

  Options: {
    label: 'Options',
    value: 'AAAAAgAAAJcAAAA2Aw==',
    x: 8,
    y: 4,
    icon: <>OPTIONS</>,
  },
  Prev: {
    label: 'Prev',
    value: 'AAAAAgAAAJcAAAA8Aw==',
    x: 3,
    y: 0,
    icon: <BackwardOutlined />,
  },
  Next: {
    label: 'Next',
    value: 'AAAAAgAAAJcAAAA9Aw==',
    x: 3,
    y: 4,
    icon: <ForwardOutlined />,
  },

  SyncMenu: {
    label: 'SyncMenu',
    value: 'AAAAAgAAABoAAABYAw==',
    x: 6,
    y: 0,
    icon: <>SYNC</>,
  },
  Hdmi1: {
    label: 'Hdmi1',
    value: 'AAAAAgAAABoAAABaAw==',
    x: 0,
    y: 0,
    icon: <>HDMI1</>,
  },
  Hdmi2: {
    label: 'Hdmi2',
    value: 'AAAAAgAAABoAAABbAw==',
    x: 0,
    y: 0,
    icon: <>HDMI2</>,
  },
  Hdmi3: {
    label: 'Hdmi3',
    value: 'AAAAAgAAABoAAABcAw==',
    x: 0,
    y: 0,
    icon: <>HDMI3</>,
  },
  Hdmi4: {
    label: 'Hdmi4',
    value: 'AAAAAgAAABoAAABdAw==',
    x: 0,
    y: 0,
    icon: <>HDMI4</>,
  },

  Analog: {
    label: 'Analog',
    value: 'AAAAAgAAAHcAAAANAw==',
    x: 10,
    y: 0,
    icon: <>ANALOG</>,
  },
  Digital: {
    label: 'Digital',
    value: 'AAAAAgAAAJcAAAAyAw==',
    x: 10,
    y: 0,
    icon: <>Digital</>,
  },
  Exit: {
    label: 'Exit',
    value: 'AAAAAQAAAAEAAABjAw==',
    x: 10,
    y: 1,
    icon: <>Exit</>,
  },
  GGuide: {
    label: 'GGuide',
    value: 'AAAAAQAAAAEAAAAOAw==',
    x: 10,
    y: 3,
    icon: <BarcodeOutlined />,
  },
  iManual: {
    label: 'iManual',
    value: 'AAAAAgAAABoAAAB7Aw==',
    x: 10,
    y: 4,
    icon: <QuestionOutlined />,
  },

  DOT: {
    label: 'DOT',
    value: 'AAAAAgAAAJcAAAAdAw==',
    x: 4,
    y: 0,
    icon: <>.</>,
  },
  SubTitle: {
    label: 'SubTitle',
    value: 'AAAAAgAAAJcAAAAoAw==',
    x: 4,
    y: 1,
    icon: <>CC</>,
  },
  Mode3D: {
    label: 'Mode3D',
    value: 'AAAAAgAAAHcAAABNAw==',
    x: 4,
    y: 3,
    icon: <>3D</>,
  },
  Rec: {
    label: 'Rec',
    value: 'AAAAAgAAAJcAAAAgAw==',
    x: 4,
    y: 4,
    icon: <>REC</>,
  },
};

const BACKUP_BUTTONS: Record<string, BaseRemoteControlAction> = {
  PowerOn: {
    label: 'PowerOn',
    value: 'AAAAAQAAAAEAAAAuAw==',
    x: 0,
    y: 4,
    icon: <PoweroffOutlined />,
  },
  TvPower: {
    label: 'TvPower',
    value: 'AAAAAQAAAAEAAAAVAw==',
    x: 0,
    y: 4,
    icon: <PoweroffOutlined />,
  },
  Tv: {
    label: 'Tv',
    value: 'AAAAAQAAAAEAAAAkAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TvInput: {
    label: 'TvInput',
    value: 'AAAAAQAAAAEAAAAlAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TvAntennaCable: {
    label: 'TvAntennaCable',
    value: 'AAAAAQAAAAEAAAAqAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  WakeUp: {
    label: 'WakeUp',
    value: 'AAAAAQAAAAEAAAAuAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  MediaAudioTrack: {
    label: 'MediaAudioTrack',
    value: 'AAAAAQAAAAEAAAAXAw==',
    x: 15,
    y: 4,
    icon: <WarningOutlined />,
  },
  Sleep: {
    label: 'Sleep',
    value: 'AAAAAQAAAAEAAAAvAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  SleepTimer: {
    label: 'SleepTimer',
    value: 'AAAAAQAAAAEAAAA2Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Analog2: {
    label: 'Analog2',
    value: 'AAAAAQAAAAEAAAA4Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TvAnalog: {
    label: 'TvAnalog',
    value: 'AAAAAQAAAAEAAAA4Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Display: {
    label: 'Display',
    value: 'AAAAAQAAAAEAAAA6Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Jump: {
    label: 'Jump',
    value: 'AAAAAQAAAAEAAAA7Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PicOff: {
    label: 'PicOff',
    value: 'AAAAAQAAAAEAAAA+Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PictureOff: {
    label: 'PictureOff',
    value: 'AAAAAQAAAAEAAAA+Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Teletext: {
    label: 'Teletext',
    value: 'AAAAAQAAAAEAAAA/Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Video1: {
    label: 'Video1',
    value: 'AAAAAQAAAAEAAABAAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Video2: {
    label: 'Video2',
    value: 'AAAAAQAAAAEAAABBAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  AnalogRgb1: {
    label: 'AnalogRgb1',
    value: 'AAAAAQAAAAEAAABDAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PictureMode: {
    label: 'PictureMode',
    value: 'AAAAAQAAAAEAAABkAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Confirm: {
    label: 'Confirm',
    value: 'AAAAAQAAAAEAAABlAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  ClosedCaption: {
    label: 'ClosedCaption',
    value: 'AAAAAgAAAKQAAAAQAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Component1: {
    label: 'Component1',
    value: 'AAAAAgAAAKQAAAA2Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Component2: {
    label: 'Component2',
    value: 'AAAAAgAAAKQAAAA3Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Wide: {
    label: 'Wide',
    value: 'AAAAAgAAAKQAAAA9Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  EPG: {
    label: 'EPG',
    value: 'AAAAAgAAAKQAAABbAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PAP: {
    label: 'PAP',
    value: 'AAAAAgAAAKQAAAB3Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TenKey: {
    label: 'TenKey',
    value: 'AAAAAgAAAJcAAAAMAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  BSCS: {
    label: 'BSCS',
    value: 'AAAAAgAAAJcAAAAQAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Ddata: {
    label: 'Ddata',
    value: 'AAAAAgAAAJcAAAAVAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  SubTitle: {
    label: 'SubTitle',
    value: 'AAAAAgAAAJcAAAAoAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  CS: {
    label: 'CS',
    value: 'AAAAAgAAAJcAAAArAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  BS: {
    label: 'BS',
    value: 'AAAAAgAAAJcAAAAsAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Media: {
    label: 'Media',
    value: 'AAAAAgAAAJcAAAA4Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  DpadCenter: {
    label: 'DpadCenter',
    value: 'AAAAAgAAAJcAAABKAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  CursorUp: {
    label: 'CursorUp',
    value: 'AAAAAgAAAJcAAABPAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  CursorDown: {
    label: 'CursorDown',
    value: 'AAAAAgAAAJcAAABQAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  CursorLeft: {
    label: 'CursorLeft',
    value: 'AAAAAgAAAJcAAABNAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  CursorRight: {
    label: 'CursorRight',
    value: 'AAAAAgAAAJcAAABOAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  ShopRemoteControlForcedDynamic: {
    label: 'ShopRemoteControlForcedDynamic',
    value: 'AAAAAgAAAJcAAABqAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  FlashPlus: {
    label: 'FlashPlus',
    value: 'AAAAAgAAAJcAAAB4Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  FlashMinus: {
    label: 'FlashMinus',
    value: 'AAAAAgAAAJcAAAB5Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  AudioQualityMode: {
    label: 'AudioQualityMode',
    value: 'AAAAAgAAAJcAAAB7Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  DemoMode: {
    label: 'DemoMode',
    value: 'AAAAAgAAAJcAAAB8Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  DigitalToggle: {
    label: 'DigitalToggle',
    value: 'AAAAAgAAAHcAAABSAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  DemoSurround: {
    label: 'DemoSurround',
    value: 'AAAAAgAAAHcAAAB7Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  '*AD': {
    label: '*AD',
    value: 'AAAAAgAAABoAAAA7Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  AudioMixUp: {
    label: 'AudioMixUp',
    value: 'AAAAAgAAABoAAAA8Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  AudioMixDown: {
    label: 'AudioMixDown',
    value: 'AAAAAgAAABoAAAA9Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PhotoFrame: {
    label: 'PhotoFrame',
    value: 'AAAAAgAAABoAAABVAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Tv_Radio: {
    label: 'Tv_Radio',
    value: 'AAAAAgAAABoAAABXAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TopMenu: {
    label: 'TopMenu',
    value: 'AAAAAgAAABoAAABgAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  PopUpMenu: {
    label: 'PopUpMenu',
    value: 'AAAAAgAAABoAAABhAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  OneTouchTimeRec: {
    label: 'OneTouchTimeRec',
    value: 'AAAAAgAAABoAAABkAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  OneTouchView: {
    label: 'OneTouchView',
    value: 'AAAAAgAAABoAAABlAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  DUX: {
    label: 'DUX',
    value: 'AAAAAgAAABoAAABzAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  FootballMode: {
    label: 'FootballMode',
    value: 'AAAAAgAAABoAAAB2Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Assists: {
    label: 'Assists',
    value: 'AAAAAgAAAMQAAAA7Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  ActionMenu: {
    label: 'ActionMenu',
    value: 'AAAAAgAAAMQAAABLAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  Help: {
    label: 'Help',
    value: 'AAAAAgAAAMQAAABNAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  TvSatellite: {
    label: 'TvSatellite',
    value: 'AAAAAgAAAMQAAABOAw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
  WirelessSubwoofer: {
    label: 'WirelessSubwoofer',
    value: 'AAAAAgAAAMQAAAB+Aw==',
    x: 0,
    y: 0,
    icon: <WarningOutlined />,
  },
};
